### ISSUE TITLE
Combine forces

### ISSUE THREAD

**Issue by SimenB** [jharris4/html-webpack-tags-plugin#4] opened 2017-04-22 06:50 UTC
Hiya! 👋

I was linked this repo, and it seems to fulfill the same purpose as my own https://github.com/SimenB/add-asset-html-webpack-plugin. What do you think about combining forces? Seems unnecessary to have 2 plugins do essentially the same thing 😄

If you'd rather not though, that's totally fine, feel free to close!

**Comment by jharris4** [comment] 2017-04-22 10:13
Hi there! Sure, we could combine forces. I had a quick look at your plugin, and they are indeed very similar. What are your thoughts about how we could proceed?

**Comment by SimenB** [comment] 2017-04-22 11:30
My initial thought is adding you as collaborator on my project and porting the features you've written here over to that (I really love the `files` option you've got). WDYT, I don't want to step on your toes? 😄

**Comment by jharris4** [comment] 2017-04-22 14:14
I don't have a strong preference as to who's project gets merged to who's, but I'm a bit short on time to devote to that effort right now.

I'd be happy to help where I can if you feel like merging anything from this project that you feel would be nice to include in yours...

**Comment by SimenB** [comment] 2017-04-23 17:03
Ported `files`: https://github.com/SimenB/add-asset-html-webpack-plugin/commit/0ae8d222ad55ad671151f7970dfc4baf8a5a13f6

Any other feature you'd like to see ported, @jharris4?

**Comment by SimenB** [comment] 2017-04-23 17:35
I added you to the repo btw 😄

**Comment by jharris4** [comment] 2017-04-23 18:05
Great, thanks. For me personally, the `append` option is particularly useful, as for something like CSS files, it's important to be able to control their occurrence order in the html file.

For example, when including bootstrap.css, I want to prepend (append: false). But when specifying custom style overrides, I want to append (append: true).

**Comment by SimenB** [comment] 2017-04-23 18:18
That also sounds like a useful option! How do you keep the order deterministic though?

**Comment by jharris4** [comment] 2017-04-23 18:38
It's just a matter of whether the plugin's assets are appended or prepended to the list of assets maintained by the HtmlWebpackPlugin. The bulk of the logic for that is here: https://github.com/jharris4/html-webpack-include-assets-plugin/blob/master/index.js#L121

**Comment by quanganhtran** [comment] 2018-10-10 07:54
This issue has been inactive for a while, but I really look forward to see this happen. At the moment one plugin has the append feature, but the other actually includes the assets to be watched by WDS. I find both capabilities very important

**Comment by jharris4** [comment] 2018-10-10 07:58
@quanganhtran can you clarify what is missing for watching with WDS?

I have projects that use `webpack-dev-middleware` and it works just fine...

**Comment by quanganhtran** [comment] 2018-10-10 08:19
@jharris4 thank you for getting back so quickly! I will explain my use case:
```
{ plugins: [
  new HtmlWebpackPlugin({ template: path.join(__dirname, 'base-index.html') }),
  new AddAssetHtmlPlugin([
    { filepath: path.resolve(__dirname, 'client-fastopt-loader.js') },
    { filepath: path.resolve(__dirname, 'client-fastopt.js') },
  ]),
]}
```
with this, above extra assets are "watched". when `client-fastopt.js` is updated, WDS triggers refresh event to the page. The problem is that the assets are "prepended", which doesn't fit my use case
```
{ plugins: [
  new HtmlWebpackPlugin({ template: path.join(__dirname, 'base-index.html') }),
  new HtmlWebpackIncludeAssetsPlugin({
      assets: [
          { path: 'client-fastopt-loader.js' },
          { path: 'client-fastopt.js' },
      ],
      append: true,
  })
]}
```
with this, assets ordering is good, but paths to the assets are just inserted as is to the HTML. Changes to the files will not trigger reload event from WDS. If I use `path.join` for these assets, my filesystem paths will be just added to the HTML.

P.s. I can see that you are on Gitter. If that is more convenient and preferable, we can discuss there in direct message. I sent you a PM

**Comment by jharris4** [comment] 2018-10-10 10:04
Creating a new issue for the WDS support improvements: #37

**Comment by jharris4** [comment] 2019-04-24 11:19
@SimenB Hi Simen, I've recently been working on this plugin for a feature that I need for this project, namely to be able to use a new `external: { packageName: 'react', variableName: 'React' }` option for assets that lets me config this plugin to split packages out from `webpack` bundles.

I've got it working, but it also **depends** on the `append` option since packages that are externalized from webpack **must** be prepended before any other webpack bundles.

Just thought I'd share since I think `append` is a critical feature that users of your plugin might also find useful.

I'm going to close this issue, but thanks again for reaching out to open it in the first place!

**Closed by jharris4** 2019-04-24 11:19 UTC
